# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17ade03fde2b70c3661cc72f29be568c25611dd214f42df919f6fb09eff5fa8a163346d45e4a2b82e3b4078b925d75706902e406dc4e24dc2869995d64db7b28

test:
  secret_key_base: f650ecea79b97d8495b3ebb333aafc240ffff3b06f345e7145b399543db007b121f0f40ea1410e97a2ac6f705c1e94ba01235d753846aadc599f256bb8d0f71f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
